version: "3.8"

services:

  frontend:
    container_name: hackaboss-frontend
    image: ednonlabs.azurecr.io/ednonlabs/hackaboss-frontend:${GIT_TAG}
    networks:
      - ednonlabs-network
    ports:
      - "8080:80"
    restart: on-failure

networks:
  ednonlabs-network:
   driver: bridge
   name: ednonlabs
   ipam:
    config:
     - subnet: 10.50.0.0/24